### ISSUE TITLE
Q42 Logo

### ISSUE THREAD

**Issue by Jesse-Kramer** [Annevd/the-startup-responsive-interactieve-website#1]
Ik ben er achter gekomen dat Q42 uitleg heeft hoe je de logo kan gebruiken. Hierbij de link https://logo.q42.com/

**Comment by Annevd** [comment]
did it :)
![image](https://github.com/Annevd/the-startup-responsive-interactieve-website/assets/144004647/150bee1e-390c-4ba5-ab3a-d108cb38fbd0)
