### ISSUE TITLE
knopje "is stiekem een designer" werkt niet

### ISSUE THREAD

**Issue by Pink-Mallow** [Annevd/the-startup-responsive-interactieve-website#15]
Als ik druk op het knopje "Is stiekem een designer" komt er niks te voor schijn. Ik weet niet of het is omdat je het nog niet hebt aangemaakt, maar als je er nog niet aan hebt gewerkt, kijk er naar ! 😃  voor de rest  ziet  het er leuk uit!!!

**Comment by Annevd** [comment]
Hi, dankjewel!!! Dit komt omdat er in de gegeven informatie van de opdrachtgever niemand is die dit filter heeft, en dus ook niemand laat zien. In dit geval is dat dus de bedoeling ⁠😃
