### ISSUE TITLE
Div's hebben geen class

### ISSUE THREAD

**Issue by zainablfz** [Annevd/the-startup-responsive-interactieve-website#18]
https://github.com/Annevd/the-startup-responsive-interactieve-website/blob/1abfacfb2514c312472964da2e5c7a87851fbaf3/the-sprint-main/public/index.html#L110-L117

https://github.com/Annevd/the-startup-responsive-interactieve-website/blob/1abfacfb2514c312472964da2e5c7a87851fbaf3/the-sprint-main/public/index.html#L131-L133

De `<div>` element om de buttons heen zit, heeft geen waarde aangezien het geen class heeft en dus dit ook niet wordt gebruikt bij de styling. 

Dit kan je oplossen door dit wel te gebruiken voor de styling dmv een class. Daarnaast kan je kijken of dit nodig is en dit te vervangen door een semantischere element of dit te verwijderen indien dit overbodig is.

Hier kan je meer lezen over de `<div>` element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div

**Comment by Annevd** [comment]
Opgelost door de onnodige divs weg te halen.
