### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by Jesse-Kramer** [Annevd/the-startup-responsive-interactieve-website#2]
Zoals je zelf al zei werkt je font nog niet helemaal. Controlleer even of dit kan komen doordat de url van de fonts niet kloppen. Dit was bij wel het geval. Dus ../fonts/... etc. Hierdoor zal dit als het goed is moeten werken.

**Comment by Annevd** [comment]
Dit heeft het inderdaad opgelost, thanks!
