### ISSUE TITLE
Misschien article toevoegen inplaats van div?

### ISSUE THREAD

**Issue by Daan645** [Annevd/the-startup-responsive-interactieve-website#22]
Je zou hier een article kunnen toevoegen inplaats van div om je html wat semantischer te maken

https://github.com/Annevd/the-startup-responsive-interactieve-website/blob/1abfacfb2514c312472964da2e5c7a87851fbaf3/the-sprint-main/public/index.html#L249C11-L255

**Comment by Annevd** [comment]
Omdat ```<section>``` en ```<article>``` het liefst een heading  bevatten zoals h1-h6 en deze dat niet heeft, denk ik dat het in dit geval misschien beter een ```<div>``` kan blijven.
