### ISSUE TITLE
Gebruik van sections en articles.

### ISSUE THREAD

**Issue by Jesse-Kramer** [Annevd/the-startup-responsive-interactieve-website#3]
Kijk of je div'jes kunt vervangen door sections/articles.

**Comment by KrijnHoetmer** [comment]
Welke precies? Kun je linken naar wat je bedoelt?

**Comment by Annevd** [comment]
Omdat de eerste plek waar ik een ```<div>``` gebruik het echt nodig is alleen voor javascript en styling, en op andere plekken het element geen heading (nodig) heeft, zijn deze denk ik handiger als ```<div>```.
