### ISSUE TITLE
Onnodige buttons?

### ISSUE THREAD

**Issue by Jesse-Kramer** [Annevd/the-startup-responsive-interactieve-website#4]
Zijn de buttons nodig die je hebt als je over een persoon hovered of kan je deze vervangen door spans of iets anders?
https://github.com/Annevd/the-startup-responsive-interactieve-website/blob/87d610ce473af05391dc103a49c8cb2239fc942d/the-sprint-main/public/index.html#L230

**Comment by Annevd** [comment]
Span is inderdaad beter, heb ik gefixt! 
![image](https://github.com/Annevd/the-startup-responsive-interactieve-website/assets/144004647/577f92a2-08fc-4103-be62-b8b1d5981247)
